language: cpp
compiler:
  - clang
before_script:
# nomlib dependencies (SDL):
  - sudo apt-get install libsdl1.2-dev libsdl1.2debian libsdl-image1.2-dev libsdl-image1.2 libsdl-ttf2.0-dev libsdl-ttf2.0-0
# nomlib dependencies (Audio):
  - sudo apt-get install libsndfile1-dev libopenal-dev
# TTcards dependencies
  - sudo apt-get install libjson-spirit-dev
  - mkdir build && cd build && cmake -DTTCARDS_NOMLIB_COMPILE=on ..
before_install:
  - git submodule update --init --recursive
script:
  - make -j4

# whitelist
branches:
  only:
    - travis
