language: cpp
compiler:
  - gcc
  #- clang
before_install:
# nomlib dependencies (SDL):
  - sudo apt-get install libsdl1.2-dev libsdl1.2debian libsdl-image1.2-dev libsdl-image1.2 libsdl-ttf2.0-dev libsdl-ttf2.0-0
# nomlib dependencies (Audio):
  - sudo apt-get install libsndfile1-dev libopenal-dev
# nomlib dependencies (misc):
  - sudo apt-get install libmagic-dev doxygen
# TTcards dependencies:
  - sudo apt-get install libboost-dev
  - sudo apt-get install libjson-spirit-dev
# virtual X11 framebuffer (not used, yet):
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x32"
# extlibs bootstrap / initialization:
  #- git submodule update --init --recursive
# nomlib build & installation:
  - PROJECT_NAME=nomlib; export PROJECT_NAME
  - git clone https://github.com/i8degrees/nomlib nomlib.git
  - cd nomlib.git && mkdir -p build && cd build
  - cmake ..
  - make -j4
  - sudo make install
  - make clean
before_script:
  - PROJECT_NAME=ttcards; export PROJECT_NAME
  - cd $HOME/build/i8degrees/${PROJECT_NAME} && mkdir -p build build-osx && cd build
  - cmake -D BUILD_POSIX=on ..
script:
  - make -j4
  - sudo make install
  - sudo make uninstall
  - make clean
# whitelist
branches:
  only:
    - dev
    - master
