language: cpp
compiler:
  - gcc
  #- clang
before_install:
# Required dependencies
  - sudo apt-get install libsdl1.2-dev libsdl1.2debian libsdl-image1.2-dev libsdl-image1.2 libsdl-ttf2.0-dev libsdl-ttf2.0-0 libsndfile1-dev libopenal-dev libmagic-dev libgtk2.0-dev #libjson-spirit-dev # doxygen graphviz
# virtual X11 framebuffer:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x32"
# nomlib build & installation:
  - PROJECT_NAME=nomlib; export PROJECT_NAME
  - git clone --branch=dev https://github.com/i8degrees/nomlib nomlib.git
  - cd nomlib.git && mkdir -p build && cd build
  - cmake -D VERBOSE=on -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j4
  - sudo make install
  - sudo ldconfig
before_script:
  - PROJECT_NAME=ttcards; export PROJECT_NAME
  - cd $HOME/build/i8degrees/${PROJECT_NAME} && mkdir -p build build-osx && cd build
  - cmake -D VERBOSE=on -D CMAKE_INSTALL_PREFIX=/usr/local ..
script:
  - make -j4
  #- make package # TODO
  #- sudo dpkg --install ttcards_0.7.0.deb
  #- sudo dpkg --remove ttcards
  - sudo make install
  - du -csh "$(which ttcards)"
  - ttcards --version
  - ttcards --export && cat $HOME/Documents/ttcards/cards.json
  - sudo make uninstall
  - make clean
# whitelist
branches:
  only:
    - travis
    - dev
    - master
