name: ci

on:
  pull_request:
  push:
    branches: [master, dev, feature/LinuxPort]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build

